# Generated by Django 4.2.5 on 2023-09-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_employee_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sexo',
        ),
    ]
