# Generated by Django 4.2.5 on 2023-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_client_detsale_product_sale_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
